spring:
  datasource:
    url: jdbc:mysql://119.91.86.79:3306/mpgdev?serverTimezone=Asia/Shanghai
    username: MPGdev
    password: S6aBKaRCJiW2YwPK
    driverClassName: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.ghstdio.pairprogram.dao.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    web: debug
    com:
      template:
        springtemplate:
          dao:
            repository: debug

token:
  expireDate: 10800000
  secret: mpg

hazelnut:
  url: https://sms_developer.zhenzikj.com/sms/send.do
  appId: 110087
  appSecret: 4120693a-d8b3-49ad-b419-49ade53964b0
  templateId: 6896
